#include "SiCKL.h"

DEFINE_MEMBER_VAR(Int2, Int, X, 0)
DEFINE_MEMBER_VAR(Int2, Int, Y, 1)

DEFINE_MEMBER_VAR(Int3, Int, X, 0)
DEFINE_MEMBER_VAR(Int3, Int, Y, 1)
DEFINE_MEMBER_VAR(Int3, Int, Z, 2)

DEFINE_MEMBER_VAR(Int4, Int, X, 0)
DEFINE_MEMBER_VAR(Int4, Int, Y, 1)
DEFINE_MEMBER_VAR(Int4, Int, Z, 2)
DEFINE_MEMBER_VAR(Int4, Int, W, 3)


DEFINE_MEMBER_VAR(UInt2, UInt, X, 0)
DEFINE_MEMBER_VAR(UInt2, UInt, Y, 1)

DEFINE_MEMBER_VAR(UInt3, UInt, X, 0)
DEFINE_MEMBER_VAR(UInt3, UInt, Y, 1)
DEFINE_MEMBER_VAR(UInt3, UInt, Z, 2)

DEFINE_MEMBER_VAR(UInt4, UInt, X, 0)
DEFINE_MEMBER_VAR(UInt4, UInt, Y, 1)
DEFINE_MEMBER_VAR(UInt4, UInt, Z, 2)
DEFINE_MEMBER_VAR(UInt4, UInt, W, 3)


DEFINE_MEMBER_VAR(Float2, Float, X, 0)
DEFINE_MEMBER_VAR(Float2, Float, Y, 1)

DEFINE_MEMBER_VAR(Float3, Float, X, 0)
DEFINE_MEMBER_VAR(Float3, Float, Y, 1)
DEFINE_MEMBER_VAR(Float3, Float, Z, 2)

DEFINE_MEMBER_VAR(Float4, Float, X, 0)
DEFINE_MEMBER_VAR(Float4, Float, Y, 1)
DEFINE_MEMBER_VAR(Float4, Float, Z, 2)
DEFINE_MEMBER_VAR(Float4, Float, W, 3)

